### ISSUE TITLE
Server Exhausted ERROR

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/help-desk-sign-in#10]
They apparently keep getting the server exhausted error. We will need to figure out why that is occurring.

**Comment by c-schwarze** [comment]
``` The message seems to be intermittent. Usually the timeclock won't load existing shifts and then will fail on new shifts.```

**Comment by mjweiberg28** [comment]
Here is the error that is occurring intermittently with the gspread APIError:

gspread.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

I've narrowed down the scope of the resource_exhausted error so it only displays when it is actually a true resource_exhausted error. From searching online through stack_overflow and github, this issue occurs with gspread where the OAuth access token needs to be refreshed at least every hour, otherwise the token is expired and it will give this "unauthenticated" error. This has to do with the top few lines in the shifts_controller.py file that give access to the spreadsheet, as the error was occurring on a line where the sheet.get_all_records() was being called and not able to access the sheet anymore after that hour had passed from when the code was last refreshed.

I'm currently testing adding a method that refreshes those credentials with every scan and every time accessing the student time clock page, which should hopefully clear up this issue. The problem is, it works normally for an hour, so I don't yet know of a better way to reproduce the error besides waiting an hour before knowing if this "unauthenticated" error is going to still pop up in my testing.
